language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
before_install:
  - yarn install
install:
  - npm install
script:
  - npm test -- -u
after_success:
  - npm run coveralls
  - "stable"
notifications:
  email: false
  slack: true
